// Generated by extendr: Do not edit by hand
//
// This file was created with the following call:
//   NULL

#include <R.h>
#include <Rinternals.h>
#include <R_ext/Rdynload.h>

// Declare Rust functions
SEXP wrap__rust_connect(SEXP uri);
SEXP wrap__rust_connection_uri(SEXP conn);
SEXP wrap__rust_table_names(SEXP conn);
SEXP wrap__rust_drop_table(SEXP conn, SEXP name);
SEXP wrap__rust_open_table(SEXP conn, SEXP name);
SEXP wrap__rust_create_table(SEXP conn, SEXP name, SEXP ipc_bytes, SEXP mode);
SEXP wrap__rust_table_name(SEXP table);
SEXP wrap__rust_table_schema_json(SEXP table);
SEXP wrap__rust_count_rows(SEXP table, SEXP filter);
SEXP wrap__rust_add_data(SEXP table, SEXP ipc_bytes, SEXP mode);
SEXP wrap__rust_delete_rows(SEXP table, SEXP predicate);
SEXP wrap__rust_update_rows(SEXP table, SEXP where_clause, SEXP columns_json);
SEXP wrap__rust_merge_insert(SEXP table, SEXP on_columns, SEXP ipc_bytes, SEXP when_matched_update_all, SEXP when_not_matched_insert_all, SEXP when_not_matched_by_source_delete);
SEXP wrap__rust_create_index(SEXP table, SEXP columns, SEXP index_type, SEXP replace, SEXP metric);
SEXP wrap__rust_list_indices(SEXP table);
SEXP wrap__rust_drop_index(SEXP table, SEXP name);
SEXP wrap__rust_add_columns(SEXP table, SEXP transforms_json);
SEXP wrap__rust_alter_columns(SEXP table, SEXP alterations_json);
SEXP wrap__rust_drop_columns(SEXP table, SEXP columns);
SEXP wrap__rust_table_version(SEXP table);
SEXP wrap__rust_list_versions(SEXP table);
SEXP wrap__rust_checkout(SEXP table, SEXP version);
SEXP wrap__rust_checkout_latest(SEXP table);
SEXP wrap__rust_restore(SEXP table);
SEXP wrap__rust_compact_files(SEXP table);
SEXP wrap__rust_cleanup_old_versions(SEXP table, SEXP older_than_days);
SEXP wrap__rust_execute_query(SEXP table, SEXP mode, SEXP qvec, SEXP ops_json);

static const R_CallMethodDef CallEntries[] = {
    {"wrap__rust_connect",                         (DL_FUNC) &wrap__rust_connect, 1},
    {"wrap__rust_connection_uri",                  (DL_FUNC) &wrap__rust_connection_uri, 1},
    {"wrap__rust_table_names",                     (DL_FUNC) &wrap__rust_table_names, 1},
    {"wrap__rust_drop_table",                      (DL_FUNC) &wrap__rust_drop_table, 2},
    {"wrap__rust_open_table",                      (DL_FUNC) &wrap__rust_open_table, 2},
    {"wrap__rust_create_table",                    (DL_FUNC) &wrap__rust_create_table, 4},
    {"wrap__rust_table_name",                      (DL_FUNC) &wrap__rust_table_name, 1},
    {"wrap__rust_table_schema_json",               (DL_FUNC) &wrap__rust_table_schema_json, 1},
    {"wrap__rust_count_rows",                      (DL_FUNC) &wrap__rust_count_rows, 2},
    {"wrap__rust_add_data",                        (DL_FUNC) &wrap__rust_add_data, 3},
    {"wrap__rust_delete_rows",                     (DL_FUNC) &wrap__rust_delete_rows, 2},
    {"wrap__rust_update_rows",                     (DL_FUNC) &wrap__rust_update_rows, 3},
    {"wrap__rust_merge_insert",                    (DL_FUNC) &wrap__rust_merge_insert, 6},
    {"wrap__rust_create_index",                    (DL_FUNC) &wrap__rust_create_index, 5},
    {"wrap__rust_list_indices",                    (DL_FUNC) &wrap__rust_list_indices, 1},
    {"wrap__rust_drop_index",                      (DL_FUNC) &wrap__rust_drop_index, 2},
    {"wrap__rust_add_columns",                     (DL_FUNC) &wrap__rust_add_columns, 2},
    {"wrap__rust_alter_columns",                   (DL_FUNC) &wrap__rust_alter_columns, 2},
    {"wrap__rust_drop_columns",                    (DL_FUNC) &wrap__rust_drop_columns, 2},
    {"wrap__rust_table_version",                   (DL_FUNC) &wrap__rust_table_version, 1},
    {"wrap__rust_list_versions",                   (DL_FUNC) &wrap__rust_list_versions, 1},
    {"wrap__rust_checkout",                        (DL_FUNC) &wrap__rust_checkout, 2},
    {"wrap__rust_checkout_latest",                 (DL_FUNC) &wrap__rust_checkout_latest, 1},
    {"wrap__rust_restore",                         (DL_FUNC) &wrap__rust_restore, 1},
    {"wrap__rust_compact_files",                   (DL_FUNC) &wrap__rust_compact_files, 1},
    {"wrap__rust_cleanup_old_versions",            (DL_FUNC) &wrap__rust_cleanup_old_versions, 2},
    {"wrap__rust_execute_query",                   (DL_FUNC) &wrap__rust_execute_query, 4},
    {NULL, NULL, 0}
};

void R_init_lancedb(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
