// Generated by extendr: Do not edit by hand
//
// This file was created with the following call:
//   NULL

#include <R.h>
#include <Rinternals.h>
#include <R_ext/Rdynload.h>

// Declare Rust functions
SEXP wrap__rust_connect(SEXP uri);
SEXP wrap__rust_connection_uri(SEXP conn);
SEXP wrap__rust_table_names(SEXP conn);
SEXP wrap__rust_open_table(SEXP conn, SEXP name);
SEXP wrap__rust_create_table(SEXP conn, SEXP name, SEXP ipc_bytes, SEXP mode);
SEXP wrap__rust_table_name(SEXP table);
SEXP wrap__rust_table_schema_json(SEXP table);
SEXP wrap__rust_count_rows(SEXP table, SEXP filter);
SEXP wrap__rust_add_data(SEXP table, SEXP ipc_bytes, SEXP mode);
SEXP wrap__rust_delete_rows(SEXP table, SEXP predicate);
SEXP wrap__rust_execute_query(SEXP table, SEXP mode, SEXP qvec, SEXP ops_json);

static const R_CallMethodDef CallEntries[] = {
    {"wrap__rust_connect",          (DL_FUNC) &wrap__rust_connect, 1},
    {"wrap__rust_connection_uri",   (DL_FUNC) &wrap__rust_connection_uri, 1},
    {"wrap__rust_table_names",      (DL_FUNC) &wrap__rust_table_names, 1},
    {"wrap__rust_open_table",       (DL_FUNC) &wrap__rust_open_table, 2},
    {"wrap__rust_create_table",     (DL_FUNC) &wrap__rust_create_table, 4},
    {"wrap__rust_table_name",       (DL_FUNC) &wrap__rust_table_name, 1},
    {"wrap__rust_table_schema_json",(DL_FUNC) &wrap__rust_table_schema_json, 1},
    {"wrap__rust_count_rows",       (DL_FUNC) &wrap__rust_count_rows, 2},
    {"wrap__rust_add_data",         (DL_FUNC) &wrap__rust_add_data, 3},
    {"wrap__rust_delete_rows",      (DL_FUNC) &wrap__rust_delete_rows, 2},
    {"wrap__rust_execute_query",    (DL_FUNC) &wrap__rust_execute_query, 4},
    {NULL, NULL, 0}
};

void R_init_lancedb(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
