# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   NULL
#
# nolint start

#' @docType package
#' @usage NULL
#' @useDynLib lancedb, .registration = TRUE
NULL

#' Connect to a LanceDB database (Rust binding)
#' @param uri Character. Database URI.
#' @return External pointer to LanceConnection.
#' @noRd
rust_connect <- function(uri) {
  .Call("wrap__rust_connect", uri)
}

#' Get connection URI (Rust binding)
#' @param conn External pointer to LanceConnection.
#' @return Character string.
#' @noRd
rust_connection_uri <- function(conn) {
  .Call("wrap__rust_connection_uri", conn)
}

#' List table names (Rust binding)
#' @param conn External pointer to LanceConnection.
#' @return Character vector of table names.
#' @noRd
rust_table_names <- function(conn) {
  .Call("wrap__rust_table_names", conn)
}

#' Open a table (Rust binding)
#' @param conn External pointer to LanceConnection.
#' @param name Character. Table name.
#' @return External pointer to LanceTable.
#' @noRd
rust_open_table <- function(conn, name) {
  .Call("wrap__rust_open_table", conn, name)
}

#' Create a table (Rust binding)
#' @param conn External pointer to LanceConnection.
#' @param name Character. Table name.
#' @param ipc_bytes Raw. Arrow IPC stream bytes.
#' @param mode Character. "create" or "overwrite".
#' @return External pointer to LanceTable.
#' @noRd
rust_create_table <- function(conn, name, ipc_bytes, mode) {
  .Call("wrap__rust_create_table", conn, name, ipc_bytes, mode)
}

#' Get table name (Rust binding)
#' @param table External pointer to LanceTable.
#' @return Character string.
#' @noRd
rust_table_name <- function(table) {
  .Call("wrap__rust_table_name", table)
}

#' Get table schema as JSON (Rust binding)
#' @param table External pointer to LanceTable.
#' @return Character string (JSON).
#' @noRd
rust_table_schema_json <- function(table) {
  .Call("wrap__rust_table_schema_json", table)
}

#' Count rows in table (Rust binding)
#' @param table External pointer to LanceTable.
#' @param filter Optional character filter string.
#' @return Integer count.
#' @noRd
rust_count_rows <- function(table, filter) {
  .Call("wrap__rust_count_rows", table, filter)
}

#' Add data to table (Rust binding)
#' @param table External pointer to LanceTable.
#' @param ipc_bytes Raw. Arrow IPC stream bytes.
#' @param mode Character. "append" or "overwrite".
#' @noRd
rust_add_data <- function(table, ipc_bytes, mode) {
  invisible(.Call("wrap__rust_add_data", table, ipc_bytes, mode))
}

#' Delete rows from table (Rust binding)
#' @param table External pointer to LanceTable.
#' @param predicate Character. SQL predicate string.
#' @noRd
rust_delete_rows <- function(table, predicate) {
  invisible(.Call("wrap__rust_delete_rows", table, predicate))
}

#' Execute a query plan (Rust binding)
#' @param table External pointer to LanceTable.
#' @param mode Character. "search" or "scan".
#' @param qvec Numeric vector or NULL.
#' @param ops_json Character. JSON-encoded operations array.
#' @return Raw vector of Arrow IPC stream bytes.
#' @noRd
rust_execute_query <- function(table, mode, qvec, ops_json) {
  .Call("wrap__rust_execute_query", table, mode, qvec, ops_json)
}

# nolint end
